
package mx.com.tecnetia.marcoproyectoseguridad.dto.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ProntipagosTopUpServiceEndPoint", targetNamespace = "http://prontipagos.ws.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ProntipagosTopUpServiceEndPoint {


    /**
     * 
     * @return
     *     returns client.ResponseBalanceTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "balanceService", targetNamespace = "http://prontipagos.ws.com", className = "mx.com.tecnetia.marcoproyectoseguridad.dto.client.BalanceService")
    @ResponseWrapper(localName = "balanceServiceResponse", targetNamespace = "http://prontipagos.ws.com", className = "mx.com.tecnetia.marcoproyectoseguridad.dto.client.BalanceServiceResponse")
    @Action(input = "http://prontipagos.ws.com/ProntipagosTopUpServiceEndPoint/balanceServiceRequest", output = "http://prontipagos.ws.com/ProntipagosTopUpServiceEndPoint/balanceServiceResponse")
    public ResponseBalanceTO balanceService();

    /**
     * 
     * @param reference
     * @param amount
     * @param clientReference
     * @param sku
     * @return
     *     returns client.TransactionResponseDto
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sellService", targetNamespace = "http://prontipagos.ws.com", className = "mx.com.tecnetia.marcoproyectoseguridad.dto.client.SellService")
    @ResponseWrapper(localName = "sellServiceResponse", targetNamespace = "http://prontipagos.ws.com", className = "mx.com.tecnetia.marcoproyectoseguridad.dto.client.SellServiceResponse")
    @Action(input = "http://prontipagos.ws.com/ProntipagosTopUpServiceEndPoint/sellServiceRequest", output = "http://prontipagos.ws.com/ProntipagosTopUpServiceEndPoint/sellServiceResponse")
    public TransactionResponseDto sellService(
        @WebParam(name = "amount", targetNamespace = "")
        Double amount,
        @WebParam(name = "reference", targetNamespace = "")
        String reference,
        @WebParam(name = "sku", targetNamespace = "")
        String sku,
        @WebParam(name = "clientReference", targetNamespace = "")
        String clientReference);

    /**
     * 
     * @return
     *     returns client.ResponseCatalogProductTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtainCatalogProducts", targetNamespace = "http://prontipagos.ws.com", className = "mx.com.tecnetia.marcoproyectoseguridad.dto.client.ObtainCatalogProducts")
    @ResponseWrapper(localName = "obtainCatalogProductsResponse", targetNamespace = "http://prontipagos.ws.com", className = "mx.com.tecnetia.marcoproyectoseguridad.dto.client.ObtainCatalogProductsResponse")
    @Action(input = "http://prontipagos.ws.com/ProntipagosTopUpServiceEndPoint/obtainCatalogProductsRequest", output = "http://prontipagos.ws.com/ProntipagosTopUpServiceEndPoint/obtainCatalogProductsResponse")
    public ResponseCatalogProductTO obtainCatalogProducts();

    /**
     * 
     * @param clientReference
     * @param transactionId
     * @return
     *     returns client.TransactionResponseTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "checkStatusService", targetNamespace = "http://prontipagos.ws.com", className = "mx.com.tecnetia.marcoproyectoseguridad.dto.client.CheckStatusService")
    @ResponseWrapper(localName = "checkStatusServiceResponse", targetNamespace = "http://prontipagos.ws.com", className = "mx.com.tecnetia.marcoproyectoseguridad.dto.client.CheckStatusServiceResponse")
    @Action(input = "http://prontipagos.ws.com/ProntipagosTopUpServiceEndPoint/checkStatusServiceRequest", output = "http://prontipagos.ws.com/ProntipagosTopUpServiceEndPoint/checkStatusServiceResponse")
    public TransactionResponseTO checkStatusService(
        @WebParam(name = "transactionId", targetNamespace = "")
        String transactionId,
        @WebParam(name = "clientReference", targetNamespace = "")
        Integer clientReference);

}
