
package mx.com.tecnetia.marcoproyectoseguridad.dto.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@org.springframework.stereotype.Service
@WebServiceClient(name = "ProntipagosTopUpServiceEndPoint", targetNamespace = "http://prontipagos.ws.com", wsdlLocation = "ProntipagosEndpoint.wsdl")
public class ProntipagosTopUpServiceEndPoint_Service
    extends Service
{

    private final static URL PRONTIPAGOSTOPUPSERVICEENDPOINT_WSDL_LOCATION;
    private final static WebServiceException PRONTIPAGOSTOPUPSERVICEENDPOINT_EXCEPTION;
    private final static QName PRONTIPAGOSTOPUPSERVICEENDPOINT_QNAME = new QName("http://prontipagos.ws.com", "ProntipagosTopUpServiceEndPoint");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
//            url = new URL("file:/Users/prlopezm/Documents/pgm/prontipagos/ProntipagosEndpoint.wsdl");
            url = new URL("file:C:/pics/ProntipagosEndpoint.wsdl");
            //url = new URL("file:/Users/carlosruiz/Documents/Público/ProntipagosEndpoint.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PRONTIPAGOSTOPUPSERVICEENDPOINT_WSDL_LOCATION = url;
        PRONTIPAGOSTOPUPSERVICEENDPOINT_EXCEPTION = e;
    }

    public ProntipagosTopUpServiceEndPoint_Service() {
        super(__getWsdlLocation(), PRONTIPAGOSTOPUPSERVICEENDPOINT_QNAME);
    }

    public ProntipagosTopUpServiceEndPoint_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), PRONTIPAGOSTOPUPSERVICEENDPOINT_QNAME, features);
    }

    public ProntipagosTopUpServiceEndPoint_Service(URL wsdlLocation) {
        super(wsdlLocation, PRONTIPAGOSTOPUPSERVICEENDPOINT_QNAME);
    }

    public ProntipagosTopUpServiceEndPoint_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PRONTIPAGOSTOPUPSERVICEENDPOINT_QNAME, features);
    }

    public ProntipagosTopUpServiceEndPoint_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProntipagosTopUpServiceEndPoint_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ProntipagosTopUpServiceEndPoint
     */
    @WebEndpoint(name = "ProntipagosTopUpServiceEndPointPort")
    public ProntipagosTopUpServiceEndPoint getProntipagosTopUpServiceEndPointPort() {
        return super.getPort(new QName("http://prontipagos.ws.com", "ProntipagosTopUpServiceEndPointPort"), ProntipagosTopUpServiceEndPoint.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProntipagosTopUpServiceEndPoint
     */
    @WebEndpoint(name = "ProntipagosTopUpServiceEndPointPort")
    public ProntipagosTopUpServiceEndPoint getProntipagosTopUpServiceEndPointPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://prontipagos.ws.com", "ProntipagosTopUpServiceEndPointPort"), ProntipagosTopUpServiceEndPoint.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PRONTIPAGOSTOPUPSERVICEENDPOINT_EXCEPTION!= null) {
            throw PRONTIPAGOSTOPUPSERVICEENDPOINT_EXCEPTION;
        }
        return PRONTIPAGOSTOPUPSERVICEENDPOINT_WSDL_LOCATION;
    }

}
